// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f config/crd/trusted-execution-clusters.io_machines.yaml
// kopium version: 0.21.3

#[allow(unused_imports)]
mod prelude {
    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "trusted-execution-clusters.io",
    version = "v1alpha1",
    kind = "Machine",
    plural = "machines"
)]
#[kube(namespaced)]
#[kube(status = "MachineStatus")]
#[kube(schema = "disabled")]
pub struct MachineSpec {
    pub id: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct MachineStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
}
