// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f config/crd/trusted-execution-clusters.io_trustedexecutionclusters.yaml
// kopium version: 0.21.3

#[allow(unused_imports)]
mod prelude {
    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "trusted-execution-clusters.io",
    version = "v1alpha1",
    kind = "TrustedExecutionCluster",
    plural = "trustedexecutionclusters"
)]
#[kube(namespaced)]
#[kube(status = "TrustedExecutionClusterStatus")]
#[kube(schema = "disabled")]
pub struct TrustedExecutionClusterSpec {
    #[serde(rename = "pcrsComputeImage")]
    pub pcrs_compute_image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "publicTrusteeAddr"
    )]
    pub public_trustee_addr: Option<String>,
    #[serde(rename = "registerServerImage")]
    pub register_server_image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "registerServerPort"
    )]
    pub register_server_port: Option<i32>,
    #[serde(rename = "trusteeImage")]
    pub trustee_image: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "trusteeKbsPort"
    )]
    pub trustee_kbs_port: Option<i32>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct TrustedExecutionClusterStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
}
